// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(path, code, deps, _package) {
    var moduleId, packageId;

    packageId = "" + _package.name + "@" + _package.version;
    moduleId = packageId + path;
    deps = deps.map(function(dep) {
      return "'" + dep + "@" + _package.dependencies[dep] + "'";
    }).join(', ');
    return "define('" + moduleId + "', [" + deps + "], function (require, exports, module) {\n    " + (code.split('\n').join('\n    ')) + "    \n})";
  };

}).call(this);
