// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(path, code, deps, pkg, opt) {
    var moduleId, packageId, useStrict;

    packageId = "" + pkg.name + "@" + pkg.version;
    moduleId = packageId + path;
    useStrict = opt.useStrict ? "'use strict';" : "";
    deps = deps.map(function(dep) {
      if (pkg.dependencies != null) {
        if (pkg.dependencies[dep] != null) {
          dep = "" + dep + "@" + pkg.dependencies[dep];
        }
      }
      return "'" + dep + "'";
    }).join(', ');
    return "" + opt.template.define + "('" + moduleId + "', [" + deps + "], function (require, exports, module) {\n    " + useStrict + "\n    " + (code.split('\n').join('\n    ')) + "    \n})";
  };

}).call(this);
