// Generated by CoffeeScript 1.6.1
(function() {

  module.exports = function(path, code, deps, pkg, opt) {
    var moduleId, packageId;
    packageId = "" + pkg.name + "@" + pkg.version;
    moduleId = packageId + path;
    deps = deps.map(function(dep) {
      return "'" + dep + "@" + pkg.dependencies[dep] + "'";
    }).join(', ');
    return "" + opt.template.define + "('" + moduleId + "', [" + deps + "], function (require, exports, module) {\n    " + (code.split('\n').join('\n    ')) + "    \n})";
  };

}).call(this);
